global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus se scrape lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ton application Spring Boot/Batch exposant les métriques via Actuator + Micrometer
  - job_name: 'quarkus-api-demo'
    metrics_path: '/q/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']