# ===== Application =====
quarkus.application.name=quarkus-health-commons-demo
quarkus.application.version=1.0.0

# ===== Base de données H2 (dev/demo) =====
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.sql-load-script=import.sql

# ===== Sécurité API Key =====
security.api-key.value=demo-secret-key
security.api-key.header=X-API-KEY
security.api-key.excluded-paths=/q/health,/q/metrics,/q/openapi,/q/swagger-ui,/swagger-ui,/api/v1/ping

# ===== OpenAPI / Swagger =====
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# ===== Métriques Prometheus =====
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.enabled=true

# ===== Logging =====
quarkus.log.level=INFO
quarkus.log.category."io.github.samiradev".level=DEBUG

quarkus.index-dependency.utils-communs.group-id=com.github.sambouch79
quarkus.index-dependency.utils-communs.artifact-id=quarkus-utils-communs
